//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigFinder.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GigFinder.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes permisos para utilizar esta funcionalidad de la aplicación..
        /// </summary>
        internal static string accesFunction {
            get {
                return ResourceManager.GetString("accesFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes permisos para acceder a este apartado de la aplicación..
        /// </summary>
        internal static string accesMenu {
            get {
                return ResourceManager.GetString("accesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acceso denegado.
        /// </summary>
        internal static string accesMenuShort {
            get {
                return ResourceManager.GetString("accesMenuShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás seguro de que quieres eliminar ese usuario?.
        /// </summary>
        internal static string askDelete {
            get {
                return ResourceManager.GetString("askDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro de que quieres eliminar ese local?.
        /// </summary>
        internal static string askDeleteLocal {
            get {
                return ResourceManager.GetString("askDeleteLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro de que quieres eliminar esa valoración?.
        /// </summary>
        internal static string askDeleteRating {
            get {
                return ResourceManager.GetString("askDeleteRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación de eliminación.
        /// </summary>
        internal static string askDeleteShort {
            get {
                return ResourceManager.GetString("askDeleteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estas seguro de que quieres eliminar ese músico?.
        /// </summary>
        internal static string askMusicianDelete {
            get {
                return ResourceManager.GetString("askMusicianDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string buttonCancelar {
            get {
                return ResourceManager.GetString("buttonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string buttonCreate {
            get {
                return ResourceManager.GetString("buttonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string buttonDelete {
            get {
                return ResourceManager.GetString("buttonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        internal static string buttonEdit {
            get {
                return ResourceManager.GetString("buttonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string buttonLogin {
            get {
                return ResourceManager.GetString("buttonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string buttonSave {
            get {
                return ResourceManager.GetString("buttonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calendario.
        /// </summary>
        internal static string calendar {
            get {
                return ResourceManager.GetString("calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gráficos.
        /// </summary>
        internal static string chart {
            get {
                return ResourceManager.GetString("chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar por.
        /// </summary>
        internal static string comboBoxFilter {
            get {
                return ResourceManager.GetString("comboBoxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguaje de canciones.
        /// </summary>
        internal static string comboBoxLang {
            get {
                return ResourceManager.GetString("comboBoxLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar.
        /// </summary>
        internal static string comboBoxMostrar {
            get {
                return ResourceManager.GetString("comboBoxMostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordenar por.
        /// </summary>
        internal static string comboBoxOrder {
            get {
                return ResourceManager.GetString("comboBoxOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de usuario:.
        /// </summary>
        internal static string comboBoxUserType {
            get {
                return ResourceManager.GetString("comboBoxUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completa todos los campos para resolver la incidencia..
        /// </summary>
        internal static string completeIncidencie {
            get {
                return ResourceManager.GetString("completeIncidencie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona un músico para editarlo..
        /// </summary>
        internal static string editMusician {
            get {
                return ResourceManager.GetString("editMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un usuario con ese correo..
        /// </summary>
        internal static string existingLocal {
            get {
                return ResourceManager.GetString("existingLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Local existente.
        /// </summary>
        internal static string existingLocalShort {
            get {
                return ResourceManager.GetString("existingLocalShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un músico con ese correo..
        /// </summary>
        internal static string existingMusician {
            get {
                return ResourceManager.GetString("existingMusician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Músico existente.
        /// </summary>
        internal static string existingMusicianShort {
            get {
                return ResourceManager.GetString("existingMusicianShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de
        ///incidencias.
        /// </summary>
        internal static string incidenciesManage {
            get {
                return ResourceManager.GetString("incidenciesManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña:.
        /// </summary>
        internal static string labelConfirPass {
            get {
                return ResourceManager.GetString("labelConfirPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud:.
        /// </summary>
        internal static string labelCoordX {
            get {
                return ResourceManager.GetString("labelCoordX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latitud.
        /// </summary>
        internal static string labelCoordY {
            get {
                return ResourceManager.GetString("labelCoordY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear local.
        /// </summary>
        internal static string labelCreateLocal {
            get {
                return ResourceManager.GetString("labelCreateLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear músico.
        /// </summary>
        internal static string labelCreateMusic {
            get {
                return ResourceManager.GetString("labelCreateMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear usuario.
        /// </summary>
        internal static string labelCreateUser {
            get {
                return ResourceManager.GetString("labelCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string labelDescription {
            get {
                return ResourceManager.GetString("labelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar local.
        /// </summary>
        internal static string labelEditLocal {
            get {
                return ResourceManager.GetString("labelEditLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar músico.
        /// </summary>
        internal static string labelEditMusic {
            get {
                return ResourceManager.GetString("labelEditMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Géneros musicales:.
        /// </summary>
        internal static string labelGendres {
            get {
                return ResourceManager.GetString("labelGendres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrantes del grupo:.
        /// </summary>
        internal static string labelGroupSize {
            get {
                return ResourceManager.GetString("labelGroupSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aforo del local:.
        /// </summary>
        internal static string labelLocalCapacity {
            get {
                return ResourceManager.GetString("labelLocalCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo:.
        /// </summary>
        internal static string labelMail {
            get {
                return ResourceManager.GetString("labelMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string labelName {
            get {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña:.
        /// </summary>
        internal static string labelPass {
            get {
                return ResourceManager.GetString("labelPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio de contratación:.
        /// </summary>
        internal static string labelPrice {
            get {
                return ResourceManager.GetString("labelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos:.
        /// </summary>
        internal static string labelSurname {
            get {
                return ResourceManager.GetString("labelSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información del local.
        /// </summary>
        internal static string localInfo {
            get {
                return ResourceManager.GetString("localInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación de locales.
        /// </summary>
        internal static string localInfoTitle {
            get {
                return ResourceManager.GetString("localInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de
        ///locales.
        /// </summary>
        internal static string LocalsManage {
            get {
                return ResourceManager.GetString("LocalsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login incorrecto.
        /// </summary>
        internal static string loginShort {
            get {
                return ResourceManager.GetString("loginShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapa.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de
        ///actividad.
        /// </summary>
        internal static string menuActivity {
            get {
                return ResourceManager.GetString("menuActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de
        ///datos.
        /// </summary>
        internal static string menuData {
            get {
                return ResourceManager.GetString("menuData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen de
        ///datos.
        /// </summary>
        internal static string menuStats {
            get {
                return ResourceManager.GetString("menuStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de
        ///usuarios.
        /// </summary>
        internal static string menuUsers {
            get {
                return ResourceManager.GetString("menuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, completa todos los campos correctamente antes de continuar..
        /// </summary>
        internal static string messageComplete {
            get {
                return ResourceManager.GetString("messageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos incompletos.
        /// </summary>
        internal static string messageCompleteShort {
            get {
                return ResourceManager.GetString("messageCompleteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y/o la contraseña son incorrectos.
        /// </summary>
        internal static string messageLogin {
            get {
                return ResourceManager.GetString("messageLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        internal static string messagePassCheck {
            get {
                return ResourceManager.GetString("messagePassCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseñas erróneas.
        /// </summary>
        internal static string messagePassCheckShort {
            get {
                return ResourceManager.GetString("messagePassCheckShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un usuario con ese correo..
        /// </summary>
        internal static string messageUserExists {
            get {
                return ResourceManager.GetString("messageUserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario existente.
        /// </summary>
        internal static string messageUserExistsShort {
            get {
                return ResourceManager.GetString("messageUserExistsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona un músico para eliminarlo..
        /// </summary>
        internal static string musicianDelete {
            get {
                return ResourceManager.GetString("musicianDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de
        ///musicos.
        /// </summary>
        internal static string musiciansManage {
            get {
                return ResourceManager.GetString("musiciansManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de
        ///valoraciones.
        /// </summary>
        internal static string ratingsManage {
            get {
                return ResourceManager.GetString("ratingsManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nota de resolución:.
        /// </summary>
        internal static string resolutionNote {
            get {
                return ResourceManager.GetString("resolutionNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de resolución:.
        /// </summary>
        internal static string resolutionState {
            get {
                return ResourceManager.GetString("resolutionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esa incidencia ya está resuelta..
        /// </summary>
        internal static string resolvedIncidencie {
            get {
                return ResourceManager.GetString("resolvedIncidencie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencia resuelta.
        /// </summary>
        internal static string resolvedIncidencieShort {
            get {
                return ResourceManager.GetString("resolvedIncidencieShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes eliminar tu propio usuario..
        /// </summary>
        internal static string sameUserDelete {
            get {
                return ResourceManager.GetString("sameUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción indebida.
        /// </summary>
        internal static string sameUserDeleteShort {
            get {
                return ResourceManager.GetString("sameUserDeleteShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, seleccione un usuario para eliminar..
        /// </summary>
        internal static string selectionDelete {
            get {
                return ResourceManager.GetString("selectionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, seleccione un usuario para editar..
        /// </summary>
        internal static string selectionEdit {
            get {
                return ResourceManager.GetString("selectionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona una incidencia para poder resolverla..
        /// </summary>
        internal static string selectionIncidencie {
            get {
                return ResourceManager.GetString("selectionIncidencie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona un local para eliminarlo..
        /// </summary>
        internal static string selectionLocalDelete {
            get {
                return ResourceManager.GetString("selectionLocalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona un local para editarlo..
        /// </summary>
        internal static string selectionLocalEdit {
            get {
                return ResourceManager.GetString("selectionLocalEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección requerida.
        /// </summary>
        internal static string selectionShort {
            get {
                return ResourceManager.GetString("selectionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, selecciona una valoración para eliminarla..
        /// </summary>
        internal static string selectRating {
            get {
                return ResourceManager.GetString("selectRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de actividad.
        /// </summary>
        internal static string titleActivity {
            get {
                return ResourceManager.GetString("titleActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar usuario.
        /// </summary>
        internal static string titleEditUser {
            get {
                return ResourceManager.GetString("titleEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resolver incidencia.
        /// </summary>
        internal static string titleIncidencie {
            get {
                return ResourceManager.GetString("titleIncidencie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de locales.
        /// </summary>
        internal static string titleLocals {
            get {
                return ResourceManager.GetString("titleLocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de músicos.
        /// </summary>
        internal static string titleMusicians {
            get {
                return ResourceManager.GetString("titleMusicians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de valoraciones.
        /// </summary>
        internal static string titleRatings {
            get {
                return ResourceManager.GetString("titleRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resumen de datos.
        /// </summary>
        internal static string titleStats {
            get {
                return ResourceManager.GetString("titleStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de usuarios.
        /// </summary>
        internal static string titleUsers {
            get {
                return ResourceManager.GetString("titleUsers", resourceCulture);
            }
        }
    }
}
