//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events()
        {
            this.Aplications = new HashSet<Aplications>();
            this.Ratings = new HashSet<Ratings>();
        }
    
        public int id { get; set; }
        public Nullable<int> musician_id { get; set; }
        public int local_id { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
        public Nullable<bool> opened_offer { get; set; }
        public int price { get; set; }
        public string description { get; set; }
        public Nullable<bool> canceled { get; set; }
        public string cancel_msg { get; set; }
        public Nullable<int> genre_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aplications> Aplications { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Locals Locals { get; set; }
        public virtual Musicians Musicians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ratings> Ratings { get; set; }
    }
}
