//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidences
    {
        public int id { get; set; }
        public string description { get; set; }
        public string admin_note { get; set; }
        public string status { get; set; }
        public int user_id { get; set; }
        public Nullable<int> admin_id { get; set; }
    
        public virtual UsersDesktop UsersDesktop { get; set; }
        public virtual Users Users { get; set; }
    }
}
