//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigFinder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dam03Entities : DbContext
    {
        public dam03Entities()
            : base("name=dam03Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aplications> Aplications { get; set; }
        public virtual DbSet<Attachments> Attachments { get; set; }
        public virtual DbSet<ChatRooms> ChatRooms { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<Incidences> Incidences { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Locals> Locals { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Musicians> Musicians { get; set; }
        public virtual DbSet<Ratings> Ratings { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersDesktop> UsersDesktop { get; set; }
        public virtual DbSet<Activity_log> Activity_log { get; set; }
    }
}
