//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigFinder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ratings
    {
        public int user_id { get; set; }
        public int event_id { get; set; }
        public string content { get; set; }
        public byte avg_rating { get; set; }
    
        public virtual Events Events { get; set; }
        public virtual Users Users { get; set; }
    }
}
